### PR TITLE
Add support for partials and include paths

### PR DESCRIPTION
**Pull request by david-driscoll**
This adds support for detecting imported partials (sass files prefixed with `_`)
This also adds support for defining import paths (supported by `node-sass` and others).

This enhances support for third party scss libraries such as foundation or bootstrap.

Examples below using Foundation 6....

image

image

### CODE REVIEW

**Comment by mrmlnc** [comment]
Hello, @david-driscoll,

Thanks for your contribution 💪 I think I need some time to inspect this PR, because your changes related to I/O. But now I can say:

  * I think we shouldn't use this async/await here –https://github.com/mrmlnc/vscode-scss/pull/37/commits/3631e28997cd00bd518b81206294f7390a66f0fd#diff-b7ecc6f2f32a4fc4bdbf497aff710f1cR137, be

**Comment by david-driscoll** [comment]
@mrmlnc sure thing I should be able to make the changes tonight.  I didn't want to bring another library in unless I had to (just to avoid any conflicts).

If you're fine with `locate-path` I'll bring that in.  Would you prefer `locatePath.sync` to avoid the extra promises that were added?

**Comment by david-driscoll** [comment]
Updated to use `locatePath.sync` 👍

**Comment by jdanyow** [comment]
Needed for primer-css because it uses `--include-path`: https://github.com/primer/primer-css#usage

Thanks for the great work!

**Comment by poorpaddy** [comment]
Is this going to be merged at some point?

**Comment by aNickzz** [comment]
👀 has this extension been abandoned?

**Comment by mrmlnc** [comment]
Sorry for trigger from bot. I think that this pull request can be closed, since most of the work is done in the `0.9.0` version.

**Pull request closed without merging**
