### PR TITLE
Feat: color preview in variables (#13)

### PR DESCRIPTION
**Pull request by jwhitmarsh**
First cut at providing this. Borrowed the color parsing code from https://github.com/sergiirocks/vscode-ext-color-highlight/tree/master/src/strategies so currently it works for hexcodes, rgb, hsl, and "words" (red, blue, etc). 

I know in #13 someone recommends using [this](https://github.com/Microsoft/vscode-css-languageservice/blob/master/src/services/cssNavigation.ts#L134) but I can't see a way to get this to work. 

I realise at this point that this is nowhere near 100% color type coverage - for instance, it doesn't handle Sass functions (`$lighten`, `$darken`, etc) - but this is a starting point.

### CODE REVIEW

**Comment by sergxp** [comment]
How do you install this on top of the marketplace one?

**Comment by jwhitmarsh** [comment]
@mrmlnc do you want some support with this extension? 

@sergxp in the mean time - (btw, this is not a pretty process)

* Clone my [repo](https://github.com/jwhitmarsh/vscode-scss) to your local machine and `cd` to it
* run `npm install && npm run clean && npm run compile`
* remove the published version of this ext: `rm -r $HOME/.vscode/extensions/mrmlnc.vscode-scss-0.6.2`
* copy my version into your extensions: `cp -R {wherever you cloned my repo to} $HOME/.vscode/extensions/mrmlnc.vscode-scss-0.6.2`

(If you're on Windows those paths are `%USERPROFILE%\.vscode\extensions`)

I wouldn't advocate this to everyone because you'll miss any updates to this repo, but it'll be useful to have other people testing this PR.

**Comment by mrmlnc** [comment]
Hello, @jwhitmarsh and @sergxp,

Sorry, guys, but https://github.com/mrmlnc/vscode-scss/issues/49#issuecomment-363537038 :(

**Comment by sergxp** [comment]
@jwhitmarsh Awesome man it works great for what I need, even if not 100%. Thanks!

**Comment by PixelT** [comment]
Any news / progress here?
@mrmlnc March / April has already passed ;)

**Comment by octref** [comment]
I rebased off master. This works for simple cases, but I guess that's already useful enough for people.

Since you are depending on https://www.npmjs.com/package/color lighten/darken would be doable as well. Maybe we'll get there one day!

**Pull request merged**
